name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          # Set always-auth in npmrc.
          always-auth: false
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          # node-version: 18.17.1
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          node-version-file: package.json
      - name: Setup NVM and yarn
        run: |
          sudo apt-get install curl
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
          corepack enable
      - name: Setup PostgreSQL Database
        run: make postgres-on-linux
      - name: Setup Environment variables
        run: | 
          cp ./packages/twenty-front/.env.example ./packages/twenty-front/.env
          cp ./packages/twenty-server/.env.example ./packages/twenty-server/.env
      - name: Install dependencies
        run: |
          nvm install
          nvm use
          yarn
      - name: Build Project
        run: |
          npx nx database:reset twenty-server
          npx nx build twenty-server
          npx nx build twenty-front
            
